elementary/wingpanel-indicator-power

src/Widgets/AppList.vala

Make sure we hexpand the app list separator

---

src/Indicator.vala
src/Services/AppManager.vala
src/Services/Backlight/Backlight.vala
src/Services/DBusInterfaces/Device.vala
src/Services/DBusInterfaces/Properties.vala
src/Services/DBusInterfaces/Screen.vala
src/Services/DBusInterfaces/UPower.vala
src/Services/Device.vala
src/Services/DeviceManager.vala
src/Services/ProcessMonitor/Monitor.vala
src/Services/ProcessMonitor/Process.vala
src/Services/SettingsManager.vala
src/Utils.vala
src/Widgets/AppList.vala
src/Widgets/DeviceList.vala
src/Widgets/DisplayWidget.vala
src/Widgets/PopoverWidget.vala
src/Widgets/ScreenBrightness.vala

Since "Wingpanel Developers" is not a legal entity

Reassign copyright from Wingpanel Developers to elementary LLC.

---

src/Widgets/AppList.vala

* Make AppRow a class instead of a method
* Don't connect signals in an extra method

AppList.vala: adjust spacing and alignment

---

src/Widgets/DeviceList.vala
src/Widgets/ScreenBrightness.vala

Some small tweaks to match alignment and spacing in the sound indicator

Match sound indicator's alignment and spacing

---

src/Widgets/AppList.vala
src/Widgets/PopoverWidget.vala

remove extra separator if there's no brightness slider

---

src/Widgets/DisplayWidget.vala

Toggle percentage with middle click

---

src/Widgets/PopoverWidget.vala

This probably doesn't look right on Loki

Use Gtk.ModelButton instead of Wingpanel button

---

src/Widgets/ScreenBrightness.vala

Update DBus name for brightness slider

---

src/Indicator.vala

Move updating visibility from get_widget to get_display_widget.

Update visibility in display widget

---

src/Widgets/PopoverWidget.vala

Check brightness slider for null

---

src/Indicator.vala
src/Widgets/PopoverWidget.vala
src/Widgets/ScreenBrightness.vala

Fixes #23 
Uses the solution from Switchboard

Update brightness slider when brightness changes

---

src/Services/DBusInterfaces/Screen.vala
src/Widgets/ScreenBrightness.vala

The Meson build file doesn't even support this build option

Drop support for old GSD

---

src/Widgets/DeviceList.vala
src/Widgets/DeviceRow.vala

The way batteries were being sorted here is kind of janky and fragile. Using ListBox gives us an actual sort method so that we could do better sorting with multiple batteries

DeviceList: Subclass ListBox

---

src/Indicator.vala
src/Services/DBusInterfaces/Device.vala
src/Services/DBusInterfaces/Properties.vala
src/Services/DBusInterfaces/UPower.vala
src/Services/Device.vala
src/Services/DeviceManager.vala
src/Widgets/DeviceRow.vala
src/Widgets/PopoverWidget.vala
src/Widgets/ScreenBrightness.vala

NOTE: There are a few vars in this project that don't follow the recommended variable naming convention, but are public. I've added ignores on the affected lines. We can also disable the rule via a config file if that'd be preferred.

lint src files with vala-lint

---

src/Services/Device.vala

https://gitlab.freedesktop.org/upower/upower/-/blob/master/libupower-glib/up-types.h

Support pen and controller batteries

---

src/Widgets/DisplayWidget.vala

DisplayWidget: Make battery percentage label translatable

---

src/Indicator.vala

Indicator: Fix gettext syntax

---

src/Widgets/AppList.vala

Also use 32px since we're trying to get away from 24px for app devs, code style, etc

AppList: Launch apps using power when clicked

---

src/Indicator.vala
src/Services/DeviceManager.vala
src/Widgets/ScreenBrightness.vala

Fixes #154 
* Move some code to DeviceManager so it is available to Indicator
* Import scrolling code from wingpanel sound indicator

Implement scroll on indicator

---

src/Services/Device.vala

When All-in-one keyboards are used. redirect to kayboard type instead of mouse type

---

src/Widgets/DeviceList.vala
src/Widgets/DeviceRow.vala
src/Widgets/PopoverWidget.vala

fixes: #3 
Open the app Gnome Power Statistics with battery info

Battery details

---

src/Services/Device.vala

Show charged

---

src/Indicator.vala

Fix touchpad scroll direction

---

src/Widgets/ScreenBrightness.vala

Same implementation as in ```io.elementary.wingpanel.sound```

Improve support for Smooth and Non-Smooth scroll events.

---

.github/workflows/main.yml
README.md
data/power.appdata.xml.in
po/pa.po
src/Indicator.vala
src/meson.build

Show scale popover when scroll on icon

---

src/Indicator.vala
src/Widgets/ScreenBrightness.vala

Fixes #209 
Main cause seems to be trying to show a notification in greeter but a couple of potentially null pointers are also checked for.

Stop wingpanel crash in greeter when scrolling on power icon

---

data/power.appdata.xml.in
meson.build

#198 and #199 are what I'm most interested in
https://github.com/elementary/wingpanel-indicator-power/compare/6.0.0...master

Release 6.1.0

---

src/Indicator.vala

Resolves the same issue as elementary/code#1213

Avoid using "Toggle"

---

src/Services/Device.vala

Show hours instead of days

---

debian/control

control: Remove libbamf3-dev

---

src/Services/Device.vala

Optimize Battery Icon Calculation and State Handling

---

debian/changelog
debian/control
debian/copyright
debian/rules

Goes with https://github.com/elementary/wingpanel-indicator-power/pull/285

Port to GTK4
