- src/Widgets/ScreenBrightness.vala
Fixes #21 
Seems there's a bug somewhere upstream of this where if you set the brightness to the same value it's already at, you end up with `brightness = brightness - 1`.
I've removed aspects of the code that were setting the brightness to the same value it was already at, but it would be good to hear from @xwing7 about lines 61-67 that "fix the first slow response". I can't tell any difference after removing them, so it would be good to know the original reason for them.
> Only update brightness if it's changed

- src/Widgets/DisplayWidget.vala
Fixes elementary/wingpanel-indicator-keyboard#10
> Center with respect to other widgets in the panel

- src/Widgets/ScreenBrightness.vala
That should fix https://github.com/elementary/wingpanel-indicator-power/issues/30.
For me issue was only when scrolling with mouse - it was using page increment which was set to 100%. Now both increments are 10%.
> Fix brightness mouse scrolling increment

- src/Indicator.vala
- src/Services/DBusInterfaces/UPower.vala
- src/Services/DeviceManager.vala
Basically we've been doing this wrong and we should use the display device of Upower to display out panel status. Tested together with my Bluetooth mouse and it does not seem to influence it.
Expected behaviour:
I can't test some of the use cases above and need some help from people with multiple batteries to confirm everything works as expected.
> Fix #13 Multi Battery by using the Upower display device for the panel

- src/Services/Device.vala
- src/Utils.vala
Show a badged tablet icon and the model name of the tablet (if it has one), rather than just a generic picture of battery with "Device" written next to it.
Before:
After:
Also adds a couple more strings for some other device types that UPower supports.
> Add support for tablets (and some other devices)

- src/Indicator.vala
- src/Utils.vala
This is overkill and doesn't add any clarity to the code. We also don't need this debug message because GtkInspector is a thing
> Simplify setting the backlight icon

- src/Indicator.vala
- src/Widgets/PopoverWidget.vala
Turn a single-use method into a lambda.
ModelButton closes the popover automatically so we don't need to do it ourselves
> PopoverWidget: simplify open settings

- src/Widgets/PopoverWidget.vala
* Use Gtk.Grid so we can specify ordering
* Use Revealers instead of creating and destroying widgets
Should make it a lot clearer what the conditions are for showing and hiding elements and what their order should be
> PopoverWidget: Rewrite as Gtk.Grid with revealers

- src/Widgets/ScreenBrightness.vala
* Gtk.Grid is horizontal by default. No need to specify
* Reduce scope of `image`
* Group attach methods
> ScreenBrightness: misc cleanup

- data/power.appdata.xml.in
- src/Widgets/DisplayWidget.vala
Since we've changed panel spacing:
> DisplayWidget: Remove label margin

- src/Services/ProcessMonitor/Monitor.vala
- src/Widgets/DeviceRow.vala
- src/Widgets/ScreenBrightness.vala
* ProcessMonitor.vala: Array cannot be property
* DeviceRow.vala: Remove unused function
* ScreenBrightness.vala: Unsafe cast; Unneeded try/catch
> Fix terminal warnings

- src/Services/DeviceManager.vala
I have a laptop (Dell XPS 15 9750) which has a wacom HID build in track pad. I discovered that the power indicator was showing this device as a battery operated device. At the time i didn't do anything hoping some one else would notice.
But lately is has become annoying to see which made me look into what this is.  Upower service registered the wacom track pad.
Here is some information:
```
kay@kay-XPS-15-9570:~$ upower -i /org/freedesktop/UPower/devices/tablet_wacom_battery_0
native-path:          wacom_battery_0
model:                Wacom HID 488F
power supply:         no
updated:              Fri 20 Nov 2020 01:58:45 PM CET (27 seconds ago)
has history:          yes
has statistics:       yes
tablet
warning-level:       none
percentage:          0%
icon-name: …
```
> Filter out weird devices

- src/Services/DBusInterfaces/UPower.vala
- src/Services/DeviceManager.vala
Since this DBus proxy gets constructed when the indicator is constructed, not when the widget is opened, it's best if we use async calls where possible.
> Use async version of Bus.get_proxy

- src/Services/Device.vala
`battery-ac-adapter` looks weird here on desktop because when this is shown, the things it indicates is the battery level of external devices (that may be wireless). So, proposing something that's power-related but not overly prescriptive
Related to https://github.com/elementary/icons/pull/1014
> Device: Use prefs system power on AC

- src/Indicator.vala
- src/Services/Device.vala
- src/Services/DeviceManager.vala
Fixes #172
* Handle failure of `upower.get_display_device ()`
* Search for power supply amongst device list if necessary
* Always connect to change in display_device property
* Modify tooltip accordingly
> Correct tooltip when no battery

- src/Indicator.vala
- src/config.vala.in
- src/meson.build
Provides the directory where the locales are actually installed.
We are [packaging this](https://github.com/NixOS/nixpkgs/pull/130380#issuecomment-895720580) in NixOS, and due to NixOS 's special `localedir`, we cannot apply the translations without this patch.
Thanks in advance for reviewing this :-)
> l10n: Correctly setup the locales

- src/Widgets/AppList.vala
Fixes #224
Adding the "Apps Using Lots of Power" as a header label of the AppList, not as a row of AppList.
> AppList: Don't add the header as a row

- src/Widgets/AppList.vala
**Merge #225 first!**
It seems like `power_eater.application.get_desktop_file ()` can return `null` if the desktop file is unavailable. For me, this happens when running several virtual machines on VirtualBox. And in this case (when the desktop file is unavailable), the power eater section in the Power Indicator only shows the header and blank rows:
This PR fixes this strange behavior. If the desktop file is unavailable and can't show any apps, simply hide the header itself too, by counting the actual number of the AppRows, instead of the number of the power eaters (which could include apps whose desktop file is available).
> AppList: Don't show the power eater section if failed to get the app

- src/Widgets/PopoverWidget.vala
Removes useless last separator in Greeter session
> Don't attach last separator when not in session

- data/power.appdata.xml.in
It looks like for the last release, the `<issues>` were added inside the `<description>` tag, making the AppData invalid. I looked at other elementary projects' AppData files, and it looks like the `<issues>` list should just be moved outside the `<description>`.
> appdata: move <issues> out of <description> to make AppData valid again

- src/Services/Device.vala
This method no longer works as of UPower 0.99.17, and simply spams the system log with warnings. It is apparently not necessary to call it.
I'm not sure whether UPower 0.99.17 will ever hit Ubuntu 22.04, but it is already part of Ubuntu 22.10, and is causing this error. Merging this now shouldn't cause any issues. (Works on my machine, as they say)
https://gitlab.freedesktop.org/upower/upower/-/commit/d0ebbe32bb5cec06335a7bd0f11f8550deaec16e
> Future: Don't call Refresh() on UPower.Device

- src/Utils.vala
Sometimes scroll gets emitted with a 0 delta. In this case we still don't want to propagate because we are usually consuming events before and after the 0 one. Noticeable when scrolling to switch workspaces is active.
> Dont propagate scroll even if the delta is 0

- src/Widgets/DeviceRow.vala
Fixed: #274
- Displays device `model` if available
- Fixes spacing when `vendor` property is not available
> Show the device model if available
